version: '3.3'
services:
  cypress:
    image: "cypress/included:3.2.0"
    network_mode: "host"
    environment:
      - CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}
      - CYPRESS_host=http://${CYPRESS_HOST}:8888/
      - CYPRESS_login=wordpress
      - CYPRESS_pass=wordpress
    working_dir: /e2e
    volumes:
      - ./:/e2e/cypress
      - ../cypress.json/:/e2e/cypress.json
    command: --record --spec /e2e/cypress/integration/${CYPRESS_SPEC_TO_RUN}


