name: Release

on:
  push:
    branches:
      - master
jobs:
  create_tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Build files using ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Release new version
        id: release
        run: |
          npm ci
          npm run release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_AUTHOR_NAME: themeisle[bot]
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_ANNOUNCEMENTS }}
          SEMANTIC_RELEASE_PACKAGE: Visualizer(free)
          GIT_AUTHOR_EMAIL: ${{ secrets.BOT_EMAIL }}
          GIT_COMMITTER_NAME: themeisle[bot]
          GIT_COMMITTER_EMAIL: ${{ secrets.BOT_EMAIL }}