name: Deploy
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Build
        run: |
          npm ci
          composer install --no-dev --prefer-dist --no-progress --no-suggest
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_THEMEISLE_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_THEMEISLE_USERNAME }}
      - name: Send update to the store
        env:
          THEMEISLE_ID: ${{ secrets.THEMEISLE_ID }}
          THEMEISLE_AUTH: ${{ secrets.THEMEISLE_STORE_AUTH }}
          STORE_URL: ${{ secrets.THEMEISLE_STORE_URL }}
          BUILD_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          if [ ! -z "$THEMEISLE_ID" ]; then
              STORE_JSON='{"version": "'$BUILD_VERSION'","id": "'$THEMEISLE_ID'","body": ""}';
              echo "$STORE_JSON";
              curl -X POST -H 'Cache-Control: no-cache' -H "Content-Type: application/json" -H "x-themeisle-auth: $THEMEISLE_AUTH"  --data "$STORE_JSON" "$STORE_URL/wp-json/edd-so/v1/update_changelog/" > /dev/null
          fi