name: PHP Tests

on:
  push:
    branches-ignore:
      - "master"

jobs:
  phplint:
    name: PHP Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: simplexml
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install composer
        run: |
          composer install --prefer-dist --no-progress
      - name: Run PHPCS
        run: composer run lint

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-22.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: simplexml, mysql
          tools: phpunit-polyfills
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install WordPress Test Suite
        run: |
          bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:${{ job.services.mysql.ports['3306'] }}
      - name: Install composer
        run: |
          composer install --prefer-dist --no-progress  --no-dev
      - name: Run phpunit
        run: phpunit
